### ISSUE TITLE
Compilation failure with gnu compiler (in initmpi.f90)

### ISSUE THREAD

**Issue by nscapin** [p-costa/SNaC#36]
Hello @p-costa, just for your info. I tried to compile the master branch of SNaC and I couldn't since MPI_LONG in initmpi.f90 was not recognized from my GNU compiler. I just replaced with MPI_INTEGER and it works fine. Anyway, I thought it was worth mentioning.

**Comment by p-costa** [comment]
Thank you, @nscapin!

The issue is that, for very large systems, `MPI_INTEGER` results in overflow. However, since this variable is not used in the calculation but only for logging purposes, it may be worth reverting or finding a more clever solution.

Perhaps the best solution is to use [`MPI_Type_match_size`](https://www.mpich.org/static/docs/latest/www3/MPI_Type_match_size.html).

**Comment by nscapin** [comment]
yes, it works for me! Thanks @p-costa.
